name: Validate

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/prepare

      - run: yarn lint
      - run: yarn build
      - run: yarn test --ci --silent
